### PR TITLE
Fix running on macos11 and check  detect network method

### PR DESCRIPTION
**Pull request by Evsio0n**
Fix running on macos11 and check  detect network method

### CODE REVIEW

**Comment by Evsio0n** [comment]
> Fix running on macos11 and check detect network method

Using bing instead of google is beacuse that some countury is banned google from firewall like China (That's we all know.)

**Comment by julian-fairfax** [comment]
Have you actually tested it on macOS Big Sur?

**Comment by Evsio0n** [comment]
Yes





发自我的iPhone


------------------ Original ------------------

**Comment by julian-fairfax** [comment]
Did the installer download correctly?

**Comment by Evsio0n** [comment]
> Did the installer download correctly?

Yes, it do have download

**Pull request closed without merging**
